name: Predictor Electricity
version: 1.0.0
slug: predictor_electricity
description: Ejecuta un script de predicci칩n de electricidad para Home Assistant
arch:
  - armhf  # Arquitectura de Raspberry Pi
startup: services
boot: auto  # Se inicia autom치ticamente con HA
ports:
  5000/tcp: 5000  # Puerto para comunicaci칩n con el script
options:
  input_sensor: ""  # Sensor de entrada, configurado desde HA
  update_interval: 3600  # Intervalo de actualizaci칩n en segundos
schema:
  input_sensor: str
  update_interval: int